name: Build and Deploy
on:
  push:
    branches: main
jobs:
  build-and-deploy:
    name: Build and deploy Gatsby Site
    runs-on: ubuntu-latest
    steps:
      - name: Restart docker container if needed
        uses: appleboy/ssh-action@v1.1.0
        with:
          host:  ${{ secrets.Host }}
          username: ${{ secrets.User }}
          key: ${{ secrets.Key }}
          port:  ${{ secrets.Port }}
          script: |
              if [ "$(docker inspect ${{ secrets.User }} --format '{{.State.Status}}')" != "running" ]; then 
                  echo "Container not running"
                  echo "Restarting container"
                  docker compose down
                  docker compose -f ./site/compose.yml up -d
              fi

      
      - name: Checkout Code
        uses: actions/checkout@v2.3.1

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'

      - name: Install Project Dependencies
        run: npm install

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli

      - name: Build
        run: gatsby build --prefix-paths

      - name: Verify build
        run: ls -la public

      - name: copy files via ssh key to temporary folder
        uses: appleboy/scp-action@master
        with:
          host:  ${{ secrets.Host }}
          username: ${{ secrets.User }}
          key: ${{ secrets.Key }}
          port:  ${{ secrets.Port }}
          source: "public/*"
          target: "/home/${{ secrets.User }}/site/root/html2"
          rm: true
          strip_components: 1

      - name: swap containers files
        uses: appleboy/ssh-action@v1.1.0
        with:
          host:  ${{ secrets.Host }}
          username: ${{ secrets.User }}
          key: ${{ secrets.Key }}
          port:  ${{ secrets.Port }}
          script: mv ./site/root/html ./site/root/html3 && mv ./site/root/html2 ./site/root/html && mv ./site/root/html3 ./site/root/html2

      - name: clean up / delete old container files
        uses: appleboy/ssh-action@v1.1.0
        with:
          host:  ${{ secrets.Host }}
          username: ${{ secrets.User }}
          key: ${{ secrets.Key }}
          port:  ${{ secrets.Port }}
          script: rm ./site/root/html2 -r
      
      
